name: openapi
version: 1.0.0
description: OpenAPI API client
homepage: homepage
authors:
  - 'Author <author@homepage>'

environment:
    sdk: ">=2.7.0 <3.0.0"
dependencies:
    dio: ^4.0.0
    built_value: ^8.0.4
    built_collection: ^5.0.0

dev_dependencies:
    built_value_generator: ^8.0.4
    build_runner: ^1.12.2
